name: muchi
description: "for my loved ones."
publish_to: 'none'
version: 1.0.4+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.20.2
  
  # File/Data handling packages
  share_plus: ^12.0.1
  file_picker: ^10.3.7
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true